In [2]:
import numpy as np

In [20]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [43]:
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr_n = arr.ndim #кол-во осей
arr_sz = arr.size #кол-во элементов в массиве
arr_sh = arr.shape#кортеж с кол-вом элементов на каждой оси
arr_dt = arr.dtype#тип данных в массиве

In [42]:
arr = np.empty([3, 3, 2])
arr

array([[[1.37962049e-306, 1.24610791e-306],
        [1.11260959e-306, 1.69109959e-306],
        [9.34603679e-307, 1.42419802e-306]],

       [[1.78019082e-306, 4.45061456e-308],
        [1.24612081e-306, 1.37962049e-306],
        [9.34597567e-307, 1.29061821e-306]],

       [[1.78019625e-306, 1.11255866e-306],
        [8.90098127e-307, 9.34609790e-307],
        [3.91792279e-317, 6.89805150e-307]]])

In [32]:
np.full([3,2,3], 2)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [33]:
np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.matrix([[1, 2, 3],[4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])